from __future__ import annotations

from pathlib import Path


ENV_FILE_PATH = Path(".env")
FILES_PATH_ENV_KEY = "FILES_PATH"
ANTHROPIC_KEY_ENV_KEY = "ANTHROPIC_KEY"
MODEL_ENV_KEY = "MODEL"
DEFAULT_FILES_PATH = Path("./test_files")
DEFAULT_MODEL = "claude-haiku-4-5-20251001"
FALLBACK_MODEL = "claude-haiku-4-5-20251001"
LLM_MAX_RETRIES = 3
LLM_RETRY_BACKOFF_SECONDS = 2.0
LLM_REQUEST_TIMEOUT_SECONDS = 60.0
LLM_MAX_TOKENS = 2000
LLM_TEMPERATURE = 0.0
LLM_MAX_INPUT_CHARS = 120_000
